### ISSUE TITLE
Error: Call to a member function setState()

### ISSUE THREAD

**Issue by cl83** [mitrpaka/commerce_klarna_checkout#4]
I'm receiving this error on checkout complete

Error: Call to a member function setState() on boolean in Drupal\commerce_klarna_checkout\Plugin\Commerce\PaymentGateway\KlarnaCheckout->onNotify() (line 230 of /app/web/modules/contrib/commerce_klarna_checkout/src/Plugin/Commerce/PaymentGateway/KlarnaCheckout.php) #0 

On line 230 I find this:
$payment->setState('completed');

I don't know if States are case-sensitive but maybe we need to change it to Completed.
See the following link:
https://docs.drupalcommerce.org/commerce2/developer-guide/orders/workflows/workflow-states

**Comment by mitrpaka** [comment]
First push notification sent from Klarna may come before or after commerce order completion (i.e. order is placed and customer redirected to "Thank You" page). 

Error described in the issue did happen when the first push notification was received before order completion. This has now been fixed. Push notification received before order completion will now be ignored.

Please note that Klarna will send the push notifications every two hours for a total of 48 hours or until order has been confirmed. The pusher works on 2 hour clock intervals.
